### ISSUE TITLE
Works for me!

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-deploy#1]
Hi! Author here. 👋

This issue is where you can attest that `ipfs-deploy` was useful to you, if you so wish :) It makes a huge difference to my motivation.

Feel free to leave any kind of positive comment here, and please open a different issue for bug reports, feature requests, and telling me off for being a n00b. I will do my best to help <3

**Comment by Stradivario** [comment]
I would love to collaborate together. I saw that you like my @rxdi/deploy package. I think it will be useful if i integrate such a tool inside rxdi/deploy instead of creating my own infrastructure. Will think about it more. 

Regards,
Kristiyan Tachev

**Comment by agentofuser** [comment]
Thank you for the interest, @Stradivario. I don't quite understand what rxdi is yet, but I'm happy to collaborate. Could you please open an issue so we can discuss how ipfs-deploy can help your project? Thank you!

**Comment by olizilla** [comment]
Works for me too!

```console
$ ipfs-deploy public
✔ 🚚 public weighs 696.0 KiB.
✔ 📌 It's pinned to Infura now with hash:
ℹ 🔗 QmW5TyREWjnrTzWHvxpYdLCDvxjWexrmb6ohf4stfKRxQj
✔ 📋 Copied public gateway URL to clipboard:
ℹ 🔗 https://ipfs.io/ipfs/QmW5TyREWjnrTzWHvxpYdLCDvxjWexrmb6ohf4stfKRxQj
✔ 🏄 Opened web browser (call with -O to disable.)
```

https://ipfs.io/ipfs/QmW5TyREWjnrTzWHvxpYdLCDvxjWexrmb6ohf4stfKRxQj/

So rad! I've got some ideas for tweaks. I'll raise some issues and PRs!

**Comment by agentofuser** [comment]
@olizilla \o/ glad you liked it. Thank you for contributing, I'm looking forward to your ideas :)

**Comment by 1v9** [comment]
https://github.com/1v9/blog/blob/master/azure-pipelines.yml#L35

Nice tool, only `npm install` takes much time o my Azure Pipelines build 😂
```bash
i 🤔  No path argument specified. Looking for common ones…
√ 📂  Found local public directory. Deploying that.
- 📦  Calculating size of public…
√ 🚚  Directory public weighs 4.1 MiB.
- 📠  Uploading and pinning to Pinata…
√ 📌  Added and pinned to Pinata with hash:
i 🔗  QmSKCfRw21iFBt9A1buRY5t7tzCRePHouBXN8nSZp1FWqT (​https://gateway.pinata.cloud/ipfs/QmSKCfRw21iFBt9A1buRY5t7tzCRePHouBXN8nSZp1FWqT/​)
- ⚙️  Validating configuration for Cloudflare…
i 📡  Beaming new hash to DNS provider Cloudflare…
(node:3964) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
√ 🙌  SUCCESS!
i 🔄  Updated DNS TXT *** to:
QmSKCfRw21iFBt9A1buRY5t7tzCRePHouBXN8nSZp1FWqT
i 🔗  dnslink=/ipfs/QmSKCfRw21iFBt9A1buRY5t7tzCRePHouBXN8nSZp1FWqT
```

**Comment by hacdias** [comment]
@1v9 yeah, we have quite a few dependencies. I'm curious: how much time did it take?

**Comment by 1v9** [comment]
@hacdias About two minutes, I didn't use some cache feature of Azure because it's a bit complicated for me.

**Comment by hacdias** [comment]
Thanks. I will try to take a look at this soon, but I do not promise anything. But I agree there are some things that we might be able to improve in order to reduce the number of dependencies!
