### ISSUE TITLE
Warn user when multiple paths exist

### ISSUE THREAD

**Issue by TripleSpeeder** [ipfs-shipyard/ipfs-deploy#112]
A standard create-react-app has both a "public" and "build" folder. The build folder is the one containing the actual build, while the "public" folder should be ignored.

Gguess-path.js just returns the first found matching folder, so you end up deploying the wrong "public" folder. 

I think one possibility would be to just bail out when more than one candidate is found with an according message to the user. Something like "Found more than one path candidate to deploy, please specify the path to use.

**Comment by hacdias** [comment]
@TripleSpeeder thanks for the suggestion. We now give an explicit error message and exit when we find more than one guessable path. This way we force users to specify it, leaving no doubts! I'm closing this then!
