### ISSUE TITLE
WebGui build with React-script, published with infura, return a string instead of the react app

### ISSUE THREAD

**Issue by ARusani** [ipfs-shipyard/ipfs-deploy#123]
I just tried deploying a WebGui  build with react-script, and after telling me that everything was uploaded, I only get a string from the ipfs.infura.io Web gateway. 

Using ipfs daemon all works fine.

![Screenshot from 2019-12-15 00-10-03](https://user-images.githubusercontent.com/37345946/70855696-646ab600-1ecf-11ea-9baf-2e826777bf30.png)

**Comment by AugustoL** [comment]
Same here

**Comment by kevinb1003** [comment]
@DeepitPK @AugustoL It works fine for me, make sure you have included `"homepage": "./"` in `package.json`

**Comment by hacdias** [comment]
I'm closing this as @kevinb1003 already provided a solution. If further questions arise, feel free to reopen.
