### ISSUE TITLE
Problem with Cloudflare DNS beaming

### ISSUE THREAD

**Issue by iJaack** [ipfs-shipyard/ipfs-deploy#124]
I got this error after configuring the .env file.
Am I making it wrong, or is it a bug?

> ℹ 📡  Beaming new hash to DNS provider Cloudflare…
> (node:12729) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
> ✖ 💔  Updating Cloudflare DNS didn't work.
> 
> HTTPError: Response code 400 (Bad Request)

**Comment by hacdias** [comment]
Hmm... I'm using Cloudflare DNS on a cron-job using `ipfs-deploy`. It's been running for months without issues so I believe it might be some credentials problem... but I can't assure you.

How're you setting your configuration? Can you send it to me, removing any keys?

**Comment by iJaack** [comment]
> Hmm... I'm using Cloudflare DNS on a cron-job using `ipfs-deploy`. It's been running for months without issues so I believe it might be some credentials problem... but I can't assure you.
> 
> How're you setting your configuration? Can you send it to me, removing any keys?

That's where I think I'm doing it wrong..
I created a .env file, with this info:
`IPFS_DEPLOY_CLOUDFLARE__API_EMAIL=[myemail]
IPFS_DEPLOY_CLOUDFLARE__API_KEY=[mykey]

IPFS_DEPLOY_CLOUDFLARE__ZONE=ipfs.jaack.me
IPFS_DEPLOY_CLOUDFLARE__RECORD=_dnslink.ipfs.jaack.me`

Maybe I'm getting my credentials wrong..  I got the key from the creation of a new API token, is that OK?

**Comment by hacdias** [comment]
@iJaack hey! There are two different things: API **KEY** and API **TOKEN**. Since you're using a token, please try using the `IPFS_DEPLOY_CLOUDFLARE__API_TOKEN` environment variable and remove the email too. However, I reiterate that the tokens are a [beta feature](https://github.com/cloudflare/node-cloudflare#api-tokens-beta). I'm personally not using them.

**Comment by iJaack** [comment]
OK, now I made a few changes and I think the credentials worked.
But I still get an error: 

> Error: zone ipfs.jaack.me couldn't be found

I set it up on Cloudflare, see the image attached.

Thank you! 
<img width="832" alt="Schermata 2019-12-23 alle 17 02 18" src="https://user-images.githubusercontent.com/6631681/71367689-15dfaa80-25a6-11ea-9211-e0f677dd4e48.png">

**Comment by iJaack** [comment]
Hi,
I made it work: in the .env files, I was putting ipfs.jaack.me as zone, it was just jaack.me instead.
I also used Pinata.cloud, that gave me a useful account page to see my pinnings.

**Comment by hacdias** [comment]
That’s great @iJaack! Hope you enjoy your dweb adventure eheh
