### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by sixcorners** [ipfs-shipyard/ipfs-deploy#129]
```
 ✖ 💔  Updating Cloudflare DNS didn't work.
32   ┌──────────────────────────────────────────────────────────────────────────┐
33   │                                                                          │
34   │ HTTPError: Response code 400 (Bad Request)                               │
35   │                                                                          │
36   └──────────────────────────────────────────────────────────────────────────┘
```

I really wish this included why.
The 403 error has an errors key in the json response that contains error messages that say why it didn't work.
I bet this 400 Bad Request response also had error messages.
This cli should output those messages.

**Comment by mikeshultz** [comment]
Truncating traces when using this as a library also doesn't help much.  Might be nice to at least turn off the formatting.

**Comment by hacdias** [comment]
On the next major version I'm working on (#208), the stack trace of the errors will be printed!
