### ISSUE TITLE
Support pinning to Eternum.io

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-deploy#13]
Continuing from https://news.ycombinator.com/item?id=19808377

The idea is to make it possible to write the authentication key to the website's `.env`, then call `ipd -p eternum` like with `-p pinata` and `-p infura` to pin to that as well.

Refs #12

**Comment by skorokithakis** [comment]
This sounds great! To pin on Eternum, all you need to do is POST the following to [https://www.eternum.io/api/pin/](https://www.eternum.io/api/pin/):

```
{
  "hash": "QmVvSSp4kf2JztYA56NxDLorr7NnQ6SGQTkyFKpr1gGQ4N",
  "name": "IPFEssay"
}
```

with `name` being optional. You also need to set the `Authorization` header with the user's token (plaintext, *not* base64 encoded): `Authorization: Token MuDNaYcSfx7YvXGKe76yHEVutEyVibe5`

**Comment by hacdias** [comment]
Superseeded by #107
