### ISSUE TITLE
hanging on upload

### ISSUE THREAD

**Issue by joeyguerra** [ipfs-shipyard/ipfs-deploy#137]

**Comment by joeyguerra** [comment]
It just hangs on:
ℹ 🤔  No path argument specified. Looking for common ones…
✔ 📂  Found local public directory. Deploying that.
✔ 🚚  Directory public weighs 6.9 MiB.
⠋ 📠  Uploading and pinning to Infura…

**Comment by hacdias** [comment]
@joeyguerra since you're using Infura, please be aware that it is a free service and there may be rate-limiting. I've never encountered such behaviour recently. Can you confirm if it now works with you?

**Comment by hacdias** [comment]
I'm closing this now. Let me know if this issue happens again!
