### ISSUE TITLE
Fails to update Cloudflare with zone limited API token

### ISSUE THREAD

**Issue by Nemo157** [ipfs-shipyard/ipfs-deploy#148]
I setup a Cloudflare API token with limited zone access

<img width="828" alt="Screenshot 2020-03-06 at 15 12 57" src="https://user-images.githubusercontent.com/81079/76090997-f78e2600-5fbc-11ea-9b72-9a64303041c4.png">

When attempting to deploy with this it fails

```
ℹ 📡  Beaming new hash to DNS provider Cloudflare…
✖ 💔  Updating Cloudflare DNS didn't work.
  │ HTTPError: Response code 403 (Forbidden)
```

If I edit the token to remove the zone limitation it works successfully.

**Comment by Macil** [comment]
This limitation is currently mentioned in the readme:

>In order to use a Cloudflare API token you need to grant zone read and dns edit permissions (both under the zone section). You also need to not restrict the zone resources to a specific zone. (This is because the list zones API call doesn't work if you only allow access to a specific zone and that is needed to look up the id of the zone you specify.)

It seems like this limitation could be solved if ipfs-deploy supported the zone id being specified in ~/.env.

**Comment by Nemo157** [comment]
Ah, whoops, I somehow missed reading that part while setting up. Being able to specify zone by id instead of name seems workable, it’s easily accessible via the UI.

It might also be worth opening an upstream issue, an API token should be able to list zones it has access to even if it can’t see them all.

**Comment by kevincox** [comment]
I would definitely like to see the ability to pass a zone id so that I can zone restrict my token.

**Comment by denzuko** [comment]
There's an easy fix and its with your cloudflare api token permissions:

![Imgur](https://i.imgur.com/JPHSLO5.png)


Under api tokens > Permissions. Ensure that you add the following:

- Account : Account Settings : Read
- Zone  : Zone Settings : Edit
- Zone : Zone : Edit
- Zone : DNS : Edit


Also when debugging; be sure to check your audit log tab.

**Comment by hacdias** [comment]
Thanks for the help here @denzuko! That should be it. I also use Cloudflare tokens and they work.
