### ISSUE TITLE
Suggestion to use fdir for better performance

### ISSUE THREAD

**Issue by thecodrr** [ipfs-shipyard/ipfs-deploy#152]
Hey, wonderful project here. I recently created **the fastest directory crawler for NodeJS** and wanted to share it with the developer community on GitHub. I couldn't help but notice that you are using `recursive-fs` which is much, much slower than `fdir`.

Would you interested in migrating to `fdir`?

[Here's my project](/thecodrr/fdir) if you are interested and I'd be happy to help where needed.

**Comment by hacdias** [comment]
Hello @thecodrr! Thanks for the suggestion. However, we're now using `globSource` that is a function that already comes with another dependency we use, the `ipfs-http-client`. I've been trying to cut in dependencies. We do not use `recursive-fs` anymore.
