### ISSUE TITLE
Make sure it's cross-platform

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-deploy#17]
- Tracking issue.
- Windows, macOS, Linux, and BSD should work as seamlessly as possible.
- Cf.: https://github.com/ehmicky/cross-platform-node-guide/blob/master/docs/summary.md

**Comment by agentofuser** [comment]
Oh yeah, there is also the browser. At some point it would be cool for everything to work straight from the browser.

**Comment by hacdias** [comment]
I'm closing this issue as there hasn't been any reports of incompatibility across different OSes. If there are any bugs, hopefully we will get them reported!
