### ISSUE TITLE
Allow just pinning CID

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs-shipyard/ipfs-deploy#181]
One of my future imagined usecases is to put ipfs-deploy at the end of a processing pipeline, which would craft directories of resources, and then append (copy, modify (add extra CID, and perform some sanity checks to maybe add precious directory as a "back reference" in a new directory), apply to ipfs) more resources to a directory resource, keeping references to old ones.

This process is best done quickest manually without ipfs-deploy (to also ensure effective deduplication), but in the end I am left with a CID which i'd want to put through ipfs-deploy to many pinning services and then some dnslinks.

Would it be possible to add a `-c`/`--cid` flag, which takes in the "directory" as a literal CID, and then starts pinning that to referenced services?

(Maybe even take in a `-i`/`--ipfs` flag, which would interpret the "directory" as a IPFS reference (`/ipfs/`, `/ipns/`, domain responding with dnslinks, etc.) and pin that instead)

**Comment by luismene** [comment]
> One of my future imagined usecases is to put ipfs-deploy at the end of a processing pipeline, which would craft directories of resources, and then append (copy, modify (add extra CID, and perform some sanity checks to maybe add precious directory as a "back reference" in a new directory), apply to ipfs) more resources to a directory resource, keeping references to old ones.
> 
> This process is best done quickest manually without ipfs-deploy (to also ensure effective deduplication), but in the end I am left with a CID which i'd want to put through ipfs-deploy to many pinning services and then some dnslinks.
> 
> Would it be possible to add a `-c`/`--cid` flag, which takes in the "directory" as a literal CID, and then starts pinning that to referenced services?
> 
> (Maybe even take in a `-i`/`--ipfs` flag, which would interpret the "directory" as a IPFS reference (`/ipfs/`, `/ipns/`, domain responding with dnslinks, etc.) and pin that instead)
