### ISSUE TITLE
Cloudflare DNS update keeps on adding TXT entries, doesn't override or remove old ones. 

### ISSUE THREAD

**Issue by besoeasy** [ipfs-shipyard/ipfs-deploy#219]
![Capture](https://user-images.githubusercontent.com/8281782/125174313-24220580-e1e2-11eb-8e6f-0c2983570052.PNG)

Well this is bad

**Comment by hacdias** [comment]
Hello @besoeasy! I've never seen this happen and I actually use ipfs-deploy in an automatic script that runs every day. I will look into this in the end of the week.

**Comment by hacdias** [comment]
Are you using the latest version?

**Comment by besoeasy** [comment]
yes i am using latest version, what kind of permission are you giving to your token ?

**Comment by besoeasy** [comment]
maybe its a issue with permission

**Comment by hacdias** [comment]
The permissions are:

![image](https://user-images.githubusercontent.com/5447088/126120195-a92965ae-a76e-4235-9ae4-fac581a9afbe.png)

**Comment by hacdias** [comment]
Did it fix it @besoeasy ?
