### ISSUE TITLE
How does this work? Does it assign a CID to the entire directory?

### ISSUE THREAD

**Issue by paulrberg** [ipfs-shipyard/ipfs-deploy#227]
Pardon me for opening an issue for a simple question (may be worth it to enable [discussions](https://docs.github.com/en/discussions) on this repo?)

I just discovered this tool and it's amazing - exactly what I needed after struggling for two hours to upload a static website with `ipfs-http-client`.

I want to understand how it works. Does this deploy every single file in the build directory recursively, upload the hash of that file to IPNS, then finally generate a CID for the entire directory? Or does it assign that to the "index.html" file? If the latter, are the relative hyperlinks in the HTML files rewritten?

**Comment by hacdias** [comment]
Hi!

> I want to understand how it works. Does this deploy every single file in the build directory recursively, upload the hash of that file to IPNS, then finally generate a CID for the entire directory?

Yes!

**Comment by paulrberg** [comment]
Great.
