### ISSUE TITLE
Deploy via IPFSpin

### ISSUE THREAD

**Issue by Exospheric** [ipfs-shipyard/ipfs-deploy#23]
For people wanting to try out IPFS-deploy, a second, account-free default in addition to Infura can be IPFSpin twitter bot. Its IPFS cluster may seem to be overloaded but it still makes big promises to the world. Lately it always replys: 

> "IPFS Cluster has been pinning this for 10 mins. This is normal for big files. Otherwise, make sure there are providers for it. Don't worry, Cluster will keep at it for a week before giving up." 

But as far as I can tell, you never know whether the pin was successful, as I never have seen a follow-up tweet to the above upon success (or failure). So a quiet request to ipfspin bot (or directly to its cluster?) via some less-noisy API might be a good thing. 

Some details of the experience: 
https://js.ipfs.io/ipns/QmZJBQBXX98AuTcoR1HBGdbe5Gph74ZBWSgNemBcqPNv1W/Zero-Config-CLI-to-Deploy-Static-Websites-to-IPFS.html

**Comment by hacdias** [comment]
Superseeded by #23
