### ISSUE TITLE
Deprecate IPFS Deploy

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-deploy#238]
IPFS Deploy was built at a time when there were no other tools to update the DNSLink and pin websites to IPFS easily. However, with time more tools have been developed and they now exist. It doesn't make sense to keep maintaining this tool while better ones exist.

Things to do:

- [ ] Put on the README that it is deprecated and list alternatives.
	- [ ] https://web3.storage and https://nft.storage, remote pinning API.
- [ ] Release NPM version to update README.
- [ ] Deprecate NPM package.
- [ ] Archive this repository.
- [ ] Move to @ipfs-inactive 

@lidel can you please get a list of all the alternatives we can list on the README? I can take care of everything except for moving the repository. I just need the alternatives which you're surely more aware of.

Also, we should consider deprecating https://github.com/ipfs-shipyard/dnslink-cloudflare if there are better alternatives, or if API changed. What do you think?

**Comment by besoeasy** [comment]
Respect & Love❤️

We had great time with this tool, specially sending and deploying websites.

**Comment by kevincox** [comment]
I'm curious for the list of alternatives. https://web3.storage/ seems just like an IPFS storage provider not an alternative to this command-line tool, I don't see the relation.

**Comment by besoeasy** [comment]
> I'm curious for the list of alternatives. https://web3.storage/ seems just like an IPFS storage provider not an alternative to this command-line tool, I don't see the relation.

you can use infura just have your own keys

**Comment by kevincox** [comment]
I also don't see how that is relevant. Infura is also a service not a CLI to make deploying sites easy.

**Comment by besoeasy** [comment]
@kevincox lot of cli tools avaiable for infura api, infact you can use ipfs lite config with infura instead of local nodes 

and use command like ipfs app

**Comment by kevincox** [comment]
What is "ipfs app" that doesn't seem to be a command.

Also there is a huge different between a tool that interacts with the API of a single provider vs a tool that:

- Uploads to one of many providers.
- Pins on one of many providers.
- Updates dns entries of money providers.

Basically this tool is a one-command option for deploying a website. I'm not aware of any alternatives here. I am considering how I would do this myself without the tool and it isn't hard but it is a lot of annoying boilerplate. I would need to do something like:

1. Upload to a provider.
2. Pin or upload to backup providers with appropriate metadata for eventual cleanup.
3. Parse out the CID from the add command.
4. Update DNS with the CID.

Plus the exact providers are slightly different for PR previews and production deploys. Having one tool that glued all of this together is super valuable. As the original description said "tools to update the DNSLink and pin websites to IPFS easily" but I am trying to find these and can't find any. So for the alternatives proposed aren't the same type of tool.
