### ISSUE TITLE
🆘 Needs Maintainer

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-deploy#242]
This issue superseeds #238, where it was discussed deprecating IFPS Deploy. We understand that this tool provides an aggregation of different APIs to both add and pin websites to IPFS, as well as update the DNSLink entries. In addition, it is clear that there are efforts by external people to improve the tool, as can be seen in the Pull Requests.

However, we do not have the necessary bandwidth to maintain this repository. From now on, the repository is marked as needing a maintainer and we do not provide active/guaranteed support until it does.

**Comment by SgtPooki** [comment]
@websoftwares, @hacdias mentioned that you want to take on maintainership of this repo, is that correct?

**Comment by websoftwares** [comment]
@SgtPooki that's right, as I already made some contributions it is for me more than logical to do it.
