### ISSUE TITLE
Add support for DNSimple

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-deploy#3]
Allow `ipfs-deploy` to update a DNSLink TXT record via the DNSimple api.

I'm happy to work on this as we need it for deploying sites for IPFS and Protocol Labs.

I'll add more details here when dig into it.

**Comment by agentofuser** [comment]
That sounds great! I don't know much about DNS in general, is this API used by other services? Is there anything like a standardized API for updating records or do we have to do it case-by-case?
