### ISSUE TITLE
Redeploy doesn't update cloudflare

### ISSUE THREAD

**Issue by posix4e** [ipfs-shipyard/ipfs-deploy#49]
So once I redeploy on cloudflare, the content doesn't update. What gives!?

**Comment by agentofuser** [comment]
- Does the DNS field get updated to the right hash?
- Does waiting a few hours for the new DNS field to propagate fix the problem?

**Comment by sixcorners** [comment]
So when I tried this recently it looks like the _dnslink records just kept being added to.
I'm looking into it.

**Comment by sixcorners** [comment]
If there are more than 20 records on the zone then the old record won't get seen. I fixed this here: ipfs-shipyard/dnslink-cloudflare#25.

**Comment by posix4e** [comment]
Hmm i see the records updating but not the domain

**Comment by sixcorners** [comment]
If you have more than two records it adds a new record instead of replacing it. Do you have two dnslink records? Do you have more than 20 records?
If not then it might be a caching issue.

**Comment by posix4e** [comment]
3 CNAMES, 5MV , 2 TXT records. I see one dnslink. It's been a day and it hasn't come back

**Comment by sixcorners** [comment]
Hasn't come back? So it's just not loading?
Are you able to get to it at ipfs.io? Does your site work if you use the old ipfs hash?
Which gateway are you using?
I have noticed that it can take a while for the gateway to find the content.

**Comment by posix4e** [comment]
I'm using pinata + infura + cloudflare.

I get a 404 from cloudflare. I see the actual hash at the pinned sites,
just not at cloudflare.

>

**Comment by posix4e** [comment]
It's all open source at

github.com/posix4e/blog
https://travis-ci.org/posix4e/blog
-> www.wuli.nu

**Comment by sixcorners** [comment]
```
$ dig txt _dnslink.www.wuli.nu +short
wuli.nu.
"ca3-1b18bd945e464afe93a084494809e1db"
$ dig +short txt www.wuli.nu
wuli.nu.
"ca3-1b18bd945e464afe93a084494809e1db"
```
There is no dnslink txt record on www.wuli.nu.

**Comment by sixcorners** [comment]
I found one here:
```
$ dig +short txt _dnslink.wuli.nu
"dnslink=/ipfs/QmQqWmk5BPEnBNhuAXPpxMRfn2Jqd5uNUkqUHp9C2ykEXY"
```
I see it responds: http://wuli.nu/
with the right info: https://ipfs.io/ipfs/QmQqWmk5BPEnBNhuAXPpxMRfn2Jqd5uNUkqUHp9C2ykEXY

**Comment by sixcorners** [comment]
I recommend making a cloudflare page rule to redirect your www to your bare domain.

**Comment by posix4e** [comment]
Something fixed it, maybe the pagelink

**Comment by sixcorners** [comment]
@posix4e http://www.wuli.nu/ is definitely still broken. There is no dnslink configured there.

**Comment by posix4e** [comment]
I am happy to add you to the cloudflare account for a bit if you wanna take
a look

TXT dnslink=/ipfs/QmUvtc3kacPHtV5o8euwtdHc3TRyokSradkSAw6nNpMp8s

[image: Screenshot_20200120_070237.png]

**Comment by sixcorners** [comment]
@posix4e www.wuli.nu and wuli.nu are two entirely different domains.
You have the txt record on the latter but not the former. When you go to www.wuli.nu it doesn't work. When you go to wuli.nu it does work.
I recommend redirecting www.wuli.nu to wuli.nu.

**Comment by posix4e** [comment]
K I think it's fixed

**Comment by sixcorners** [comment]
Cool! glad it's working.

**Comment by sixcorners** [comment]
I think this can be closed.
