### ISSUE TITLE
returns incorrect hash when upload is interrupted

### ISSUE THREAD

**Issue by MichaelMure** [ipfs-shipyard/ipfs-deploy#55]
https://github.com/agentofuser/ipfs-deploy/blob/master/index.js#L147

If the request fail due to a timeout or another reason, ipfs-deploy use the last received hash as the root hash. However, there is no guarantee that it's actually the root hash, and it won't be if the response has been truncated.

**Comment by agentofuser** [comment]
Nice catch! Thank you for reporting this. Yeah I guess the best thing is to calculate that hash locally before uploading and then verify it matches the response. Also reduces need for trust in the pinning service.

Would you like to work on this?

**Comment by hacdias** [comment]
I think this might've been fixed on the latest release. For most services, we now make sure we actually check the results for the CID of the root folder instead of just using the last one. Could you please check for me?

**Comment by hacdias** [comment]
I'm closing this. However, if this bug shows up again, please let me know.
