### ISSUE TITLE
Move to React for the CLI (Pastel)

### ISSUE THREAD

**Issue by agentofuser** [ipfs-shipyard/ipfs-deploy#7]
Using Pastel (an Ink framework by Ink's author) would make it easier to add interactivity, like asking for credentials when they are missing, allowing the user to pick services from a list, and in general allowing an alternative UX to command line parameters. Also a great source of snazzy pretty things :)

https://github.com/vadimdemedes/pastel

A first PR would be to just set up a skeleton and convert what's already there to Pastel without changing anything user-facing.

**Comment by hacdias** [comment]
I'm closing this as the package underwent a complete revamp recently.
