### ISSUE TITLE
Just pin

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-deploy#74]
Some pinning services (such as Piñata or IPFS Cluster) allow us to just pin the hash instead of 'uploading' everything at the time. For instance, if I'd like to be able to 'upload' my files to IPFS Cluster and then use that hash to pin on Piñata via their API instead of 'uploading' to both services.

Perhaps we could use a different flag. Maybe, by default, we'd 'upload' it to all services and if we set `--hash-from <service>` it would use the hash given by that service and then pin on the others.

**Comment by agentofuser** [comment]
Hmm that is a good idea! Originally I used the pin-by-hash feature from Pinata, but I didn't want to require a local node with open ports etc as it made it impossible to deploy from CI.

But if it first http-uploads to one pinning service, there is no reason why the following ones can't use the hash from it, just have to sequence things right.

I would gladly accept it if you choose to add this feature.

**Comment by ShadowJonathan** [comment]
@hacdias is this feature completed with the addition of "unique pinners"? (These upload the resource to one pinner service, and pins it on the rest)

**Comment by hacdias** [comment]
It is indeed @ShadowJonathan!
