### ISSUE TITLE
Why Prettier

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-deploy#77]
@agentofuser I was wondering why did you choose prettier to lint the code. Just wondering since most of the time I've seen [standard.js](https://standardjs.com/) being used which seems much more cleaner (less commas, more spaces, etc).

**Comment by agentofuser** [comment]
I've never used standard.js or worked on a project that used it, so Prettier was the choice I was familiar with. Now that I look at it, it seems like they have different scopes. Prettier is a more general formatter "framework", with support for a bunch of programming languages, html, markdown, css, graphql, typescript, php, etc. And even for standard.js =) https://github.com/sheerun/prettier-standard

Also, I've been starting all new projects with typescript and would like to port ipfs-deploy to it eventually, and standard.js doesn't seem to have plans to support that.

As it seems that standard.js conventions can be expressed in prettier configurations, if there are any particular ones that you'd like to start using, feel free to propose changes to the `.prettierrc`. I think the only settings I'm particularly attached to are the 79 char width limit (for 80 char terminals, leaving a character for +/- diff annotation) and the markdown proseWrap 🤓

**Comment by hacdias** [comment]
I'm closing this due to #80. I removed prettier and some other settings due to reasons mentioned on the PR.
