### ISSUE TITLE
Cloudflare dns 

### ISSUE THREAD

**Issue by tatecarson** [ipfs-shipyard/ipfs-deploy#83]
How do I setup my domain to resolve when using www? This is probably a simple fix but I'm not super well versed in DNS. My [site](https://tatecarson.com) is currently working when using the root domain, but the www 404s. I tried to follow along with [these](https://www.cloudflare.com/distributed-web-gateway/#connectingyourwebsite) instructions but might have missed something. Here are my current DNS records: 

```
CNAME www cloudflare-ipfs.com DNS Only 
CNAME tatecarson.com cloudflare-ipfs.com DNS Only 
TXT _dnslink dnslink=/ipfs/QmRFciUgPdWYpvFWcMWHEhcMndSeACMUhwVgZVcAmd5RF3 DNS only
```

and the env setup. I see that I have it going to the root here but not sure what else to put.  
```
IPFS_DEPLOY_CLOUDFLARE__ZONE=tatecarson.com
IPFS_DEPLOY_CLOUDFLARE__RECORD=_dnslink.tatecarson.com
```
 Any ideas? 

Thank you, and I realize this isn't the best place to ask but I have no other idea where to go.

**Comment by hacdias** [comment]
Hey @tatecarson!

You will also need to have a `TXT _dnslink.www` with the CID as you have for the root domain. That way, when you go to `www.yourdomain.com`, you get served the content of `_dnslink.www`.

**Comment by tatecarson** [comment]
That worked! I was unfamiliar with the dnslink record.
